export default class DotaAliases {
    log(method: string, message: string): void {
        console.log(`[DOTA ALIASES] [${method}]: ${message}`)
    }

    private heroes: string[] = [
        'anti mage',
        'axe',
        'bane',
        'bloodseeker',
        'crystal maiden',
        'drow ranger',
        'earthshaker',
        'juggernaut',
        'mirana',
        'shadow fiend',
        'morphling',
        'phantom lancer',
        'puck',
        'pudge',
        'razor',
        'sand king',
        'storm spirit',
        'sven',
        'tiny',
        'vengeful spirit',
        'windranger',
        'zeus',
        'kunkka',
        'lina',
        'lich',
        'lion',
        'shadow shaman',
        'slardar',
        'tidehunter',
        'witch doctor',
        'riki',
        'enigma',
        'tinker',
        'sniper',
        'necrophos',
        'warlock',
        'beastmaster',
        'queen of pain',
        'venomancer',
        'faceless void',
        'wraith king',
        'death prophet',
        'phantom assassin',
        'pugna',
        'templar assassin',
        'viper',
        'luna',
        'dragon knight',
        'dazzle',
        'clockwerk',
        'leshrac',
        "nature's prophet",
        'lifestealer',
        'dark seer',
        'clinkz',
        'omniknight',
        'enchantress',
        'huskar',
        'night stalker',
        'broodmother',
        'bounty hunter',
        'weaver',
        'jakiro',
        'batrider',
        'chen',
        'spectre',
        'doom',
        'ancient apparition',
        'ursa',
        'spirit breaker',
        'gyrocopter',
        'alchemist',
        'invoker',
        'silencer',
        'outworld devourer',
        'lycan',
        'brewmaster',
        'shadow demon',
        'lone druid',
        'chaos knight',
        'meepo',
        'treant protector',
        'ogre magi',
        'undying',
        'rubick',
        'disruptor',
        'nyx assassin',
        'naga siren',
        'keeper of the light',
        'io',
        'visage',
        'slark',
        'medusa',
        'troll warlord',
        'centaur warrunner',
        'magnus',
        'timbersaw',
        'bristleback',
        'tusk',
        'skywrath mage',
        'abaddon',
        'elder titan',
        'legion commander',
        'ember spirit',
        'earth spirit',
        'terrorblade',
        'phoenix',
        'oracle',
        'techies',
        'winter wyvern',
        'arc warden',
        'underlord',
        'monkey king',
        'pangolier',
        'dark willow',
        'grimstroke',
        'mars',
        'void spirit',
        'snapfire',
    ]


    private aliases = [
        { alias: 'am', name: 'anti mage' },
        { alias: 'bs', name: 'bloodseeker' },
        { alias: 'cm', name: 'crystal maiden' },
        { alias: 'drow', name: 'drow ranger' },
        { alias: 'es', name: 'earthshaker' },
        { alias: 'jugg', name: 'juggernaut' },
        { alias: 'potm', name: 'mirana' },
        { alias: 'sf', name: 'shadow fiend' },
        { alias: 'morph', name: 'morphling' },
        { alias: 'pl', name: 'phantom lancer' },
        { alias: 'sk', name: 'sand king' },
        { alias: 'storm', name: 'storm spirit' },
        { alias: 'vs', name: 'vengeful spirit' },
        { alias: 'wr', name: 'windranger' },
        { alias: 'rhasta', name: 'shadow shaman' },
        { alias: 'tide', name: 'tidehunter' },
        { alias: 'wd', name: 'witch doctor' },
        { alias: 'nigma', name: 'enigma' },
        { alias: 'necro', name: 'necrophos' },
        { alias: 'bm', name: 'beastmaster' },
        { alias: 'qop', name: 'queen of pain' },
        { alias: 'veno', name: 'venomancer' },
        { alias: 'void', name: 'faceless void' },
        { alias: 'wk', name: 'wraith king' },
        { alias: 'dp', name: 'death prophet' },
        { alias: 'pa', name: 'phantom assassin' },
        { alias: 'ta', name: 'templar assassin' },
        { alias: 'dk', name: 'dragon knight' },
        { alias: 'clock', name: 'clockwerk' },
        { alias: 'np', name: "nature's prophet" },
        { alias: 'naix', name: 'lifestealer' },
        { alias: 'ds', name: 'dark seer' },
        { alias: 'omni', name: 'omniknight' },
        { alias: 'enchant', name: 'enchantress' },
        { alias: 'ns', name: 'night stalker' },
        { alias: 'brood', name: 'broodmother' },
        { alias: 'bh', name: 'bounty hunter' },
        { alias: 'jak', name: 'jakiro' },
        { alias: 'bad', name: 'batrider' },
        { alias: 'spec', name: 'spectre' },
        { alias: 'aa', name: 'ancient apparition' },
        { alias: 'sb', name: 'spirit breaker' },
        { alias: 'gyro', name: 'gyrocopter' },
        { alias: 'alch', name: 'alchemist' },
        { alias: 'od', name: 'outworld devourer' },
        { alias: 'brew', name: 'brewmaster' },
        { alias: 'sd', name: 'shadow demon' },
        { alias: 'ld', name: 'lone druid' },
        { alias: 'ck', name: 'chaos knight' },
        { alias: 'treant', name: 'treant protector' },
        { alias: 'ogre', name: 'ogre magi' },
        { alias: 'undy', name: 'undying' },
        { alias: 'rub', name: 'rubick' },
        { alias: 'disrupt', name: 'disruptor' },
        { alias: 'nyx', name: 'nyx assassin' },
        { alias: 'naga', name: 'naga siren' },
        { alias: 'kotl', name: 'keeper of the light' },
        { alias: 'wisp', name: 'io' },
        { alias: 'dusa', name: 'medusa' },
        { alias: 'troll', name: 'troll warlord' },
        { alias: 'cent', name: 'centaur warrunner' },
        { alias: 'mag', name: 'magnus' },
        { alias: 'timber', name: 'timbersaw' },
        { alias: 'bb', name: 'bristleback' },
        { alias: 'sky', name: 'skywrath mage' },
        { alias: 'et', name: 'elder titan' },
        { alias: 'lc', name: 'legion commander' },
        { alias: 'ember', name: 'ember spirit' },
        { alias: 'tb', name: 'terrorblade' },
        { alias: 'ww', name: 'winter wyvern' },
        { alias: 'arc', name: 'arc warden' },
        { alias: 'mk', name: 'monkey king' },
        { alias: 'pango', name: 'pangolier' },
        { alias: 'willow', name: 'dark willow' },
        { alias: 'grim', name: 'grimstroke' },
        { alias: 'snap', name: 'snapfire' }]

    isFormalHeroName(hero: string): boolean {
        const formattedHero = hero.toLowerCase()
        if (!this.heroes.includes(formattedHero) || hero === "") {
            this.log("isHeroName", `${formattedHero} not listed in formal heroes' names array`)
            return false
        }

        return this.heroes.includes(formattedHero)
    }

    isHeroAlias(query: string): boolean {
        const aliasChecker = this.aliases.map((hero) => hero.alias).includes(query)
        return aliasChecker
    }

    getHeroAlias(query: string): string {
        const aliasName = this.aliases
            .filter((hero) => hero.alias === query)
            .map((hero) => hero.name)
            .toString()
        this.log("getHeroAlias", `The name: ${query} has the alias ${aliasName}`)
        return aliasName
    }
}
